% Copyright (c) 1997-2000 by TH Technology, Inc.
% All Rights Reserved.
% Date: 2006/01/02
clear
clf reset
set(gcf, 'unit' , 'normalized' , 'position' ,[0.18,0.2,0.65,0.5]);
set(gcf, 'defaultuicontrolunits' , 'normalized' );
set(gcf, 'defaultuicontrolhorizontal' , 'left' );
str='信号的基本运算';
set(gcf, 'name' ,str,'color',[0.7 0.7 0.9], 'numbertitle' , 'off' ); % 书写图形窗名
h_axes=axes( 'position' ,[0.08,0.15,0.53,0.75]); % 定义轴位框位置

h_text=uicontrol(gcf,'Style','frame',...
'unit' , 'normalized' , 'backgroundcolor',[0.4 0.4 0.5], 'position' ,[0.63,0.11,0.356,0.79], ...
'horizontal' , 'left' ,'fontsize' ,11);

xlabel('t(s)');ylabel('幅度(V)');grid on;
h_push9=uicontrol(gcf, 'style' , 'push' , ...
'unit' , 'normalized' , 'foregroundcolor','k','backgroundcolor',[0.3 0.8 0.6],'fontname',' 隶书' ,'position' ,[0.65,0.18,0.15,0.11], ...
'fontsize' ,11,'string' , '其他运算' , ...
'callback' , 'xhdqtys');
h_push1=uicontrol(gcf, 'style' , 'push' , ...
'unit' , 'normalized' ,'foregroundcolor','k','backgroundcolor',[0.3 0.8 0.6],'fontname',' 隶书' , 'position' ,[0.65,0.72,0.15,0.11], ...
'string' , '相  加' ,'fontsize' ,11, 'callback' , 'xhdxj' );
h_push2=uicontrol(gcf, 'style' , 'push' , ...
'unit' , 'normalized' ,'foregroundcolor','k','backgroundcolor',[0.3 0.8 0.6], 'fontname',' 隶书' ,'position' ,[0.82,0.72,0.15,0.11], ...
'string' , '相  乘' ,'fontsize' ,11, 'callback' , 'xhdxc' );
h_push4=uicontrol(gcf, 'style' , 'push' , ...
'unit' , 'normalized' ,'foregroundcolor','k', 'backgroundcolor',[0.3 0.8 0.6],'fontname',' 隶书' ,'position' ,[0.82,0.45,0.15,0.11], ...
'string' , '卷积积分' ,'fontsize' ,11, 'callback' , 'xhjjjj' );
h_push7=uicontrol(gcf, 'style' , 'push' , ...
'unit' , 'normalized' , 'foregroundcolor','k','backgroundcolor',[0.3 0.8 0.6],'fontname',' 隶书' ,'position' ,[0.65,0.45,0.15,0.11], ...
'fontsize' ,11,'string' , '卷积和' , ...
'callback' , 'xhjjh');
h_push8=uicontrol(gcf, 'style' , 'push' , ...
'unit' , 'normalized' , 'foregroundcolor','k','fontsize' ,11,'backgroundcolor',[0.9 0.7 0.6],'fontname',' 隶书' ,'position' ,[0.82,0.18,0.15,0.11], ...
'string' , '返  回' ,'callback' , 'xhjbys');