% Copyright (c) 1997-2000 by TH Technology, Inc.
% All Rights Reserved.
% Date: 2006/01/02
clear
clf reset
H=axes( 'unit' , 'normalized' , 'position' ,[0,0,1,1], 'visible' , 'off' );
set(gcf, 'currentaxes' ,H);
h_fig=get(H, 'parent' );
set(h_fig, 'unit' , 'normalized' , 'position' ,[0.18,0.2,0.65,0.5]);
str= ' 信号的相加 ' ;
set(gcf, 'name' ,str, 'color',[0.7 0.7 0.9],'numbertitle' , 'off' ); % 书写图形窗名
h_axes=axes( 'position' ,[0.08,0.15,0.58,0.75]); % 定义轴位框位置
xlabel('t(s)');ylabel('幅度(V)');grid on;
h_text=uicontrol(gcf,'Style','frame',...
'unit' , 'normalized' , 'backgroundcolor',[0.4 0.4 0.5], 'position' ,[0.695,0.11,0.275,0.79], ...
'horizontal' , 'left' ,'fontsize' ,11);

h_text=uicontrol(h_fig, 'style' , 'text' , ...
'unit' , 'normalized' , 'HorizontalAlignment','left','position' ,[0.73,0.765,0.21,0.1], ...
'horizontal' , 'left' , 'fontsize' ,11,'fontname',' 隶书' ,'foregroundcolor','k','backgroundcolor',[0.3 0.8 0.6],'string' ,{ 'x(t)'});
h_popup = uicontrol(h_fig, 'Style','popupmenu','fontsize' ,9,'foregroundcolor','k','Units','normalized','Position',[0.73 0.67 0.21 0.15],'BackgroundColor','white','String',{'正弦信号','余弦信号','单位斜坡信号','单边指数信号','指数函数信号','抽样函数信号','单位阶跃函数'});
h_text=uicontrol(h_fig, 'style' , 'text' , ...
'unit' , 'normalized' , 'HorizontalAlignment','left','position' ,[0.73,0.585,0.21,0.1], ...
'horizontal' , 'left' , 'fontsize' ,11,'fontname',' 隶书' ,'foregroundcolor','k','backgroundcolor',[0.3 0.8 0.6],'string' ,{ 'h(t)'});
h_popup1 = uicontrol(h_fig, 'Style','popupmenu','fontsize' ,9,'foregroundcolor','k','Units','normalized','Position',[0.73 0.49 0.21 0.15],'BackgroundColor','white','String',{'正弦信号','余弦信号','单位斜坡信号','单边指数信号','指数函数信号','抽样函数信号','单位阶跃函数'});
h_push=uicontrol(h_fig, 'style' , 'push' , ...
'unit' , 'normalized' ,'foregroundcolor','k', 'backgroundcolor',[0.3 0.8 0.6],'position' ,[0.73,0.36,0.21,0.11], ...
'fontname',' 隶书' ,'fontsize' ,11,'string' , '开  始  仿  真' , 'callback' , [  'xhxjsf(h_popup,h_popup1,h_axes)' ] );
h_push=uicontrol(h_fig, 'style' , 'push' , ...
'unit' , 'normalized' ,'foregroundcolor','k', 'backgroundcolor',[0.9 0.7 0.6],'position' ,[0.73,0.16,0.21,0.11], ...
'fontname',' 隶书' ,'fontsize' ,11,'string' , '返  回  目  录' , 'callback' , 'xhdjbys' );
