% Copyright (c) 1997-2000 by TH Technology, Inc.
% All Rights Reserved.
% Date: 2006/01/02
clear
clf reset
H=axes( 'unit' , 'normalized' , 'position' ,[0,0,1,1], 'visible' , 'off' );
set(gcf, 'currentaxes' ,H);
h_fig=get(H, 'parent' );
set(h_fig, 'unit' , 'normalized' , 'position' ,[0.18,0.2,0.6,0.5]);
str= ' 信号卷积的仿真简介 ' ;
set(gcf, 'name' ,str, 'color',[0.7 0.7 0.9],'numbertitle' , 'off' ); % 书写图形窗名

h_text=uicontrol(h_fig, 'style' , 'text' , ...
'unit' , 'normalized' , 'HorizontalAlignment','left','position' ,[0.7,0.805,0.765,0.1], ...
'horizontal' , 'left' , 'fontsize' ,11,'fontname',' 隶书' ,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9],'string' ,{ 'x(t)'});
h_popup = uicontrol(h_fig, 'Style','popupmenu','fontsize' ,9,'foregroundcolor','blue','Units','normalized','Position',[0.7 0.7 0.21 0.15],'BackgroundColor','white','String',{'正弦信号','余弦信号','单位斜坡信号','单位抛物波信号','指数函数信号','抽样函数信号','单位阶跃函数'});
h_text=uicontrol(h_fig, 'style' , 'text' , ...
'unit' , 'normalized' , 'HorizontalAlignment','left','position' ,[0.7,0.625,0.765,0.1], ...
'horizontal' , 'left' , 'fontsize' ,11,'fontname',' 隶书' ,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9],'string' ,{ 'h(t)'});
h_popup1 = uicontrol(h_fig, 'Style','popupmenu','fontsize' ,9,'foregroundcolor','blue','Units','normalized','Position',[0.7 0.52 0.21 0.15],'BackgroundColor','white','String',{'正弦信号','余弦信号','单位斜坡信号','单位抛物波信号','指数函数信号','抽样函数信号','单位阶跃函数'});
h_push=uicontrol(h_fig, 'style' , 'push' , ...
'unit' , 'normalized' ,'foregroundcolor','blue', 'backgroundcolor',[0.7 0.7 0.9],'position' ,[0.7,0.38,0.21,0.11], ...
'fontsize' ,11,'string' , '开  始  仿  真' , 'callback' , ['xhjjhs3(h_popup,h_popup1)' ] );
h_push=uicontrol(h_fig, 'style' , 'push' , ...
'unit' , 'normalized' ,'foregroundcolor','blue', 'backgroundcolor',[0.7 0.7 0.9],'position' ,[0.7,0.18,0.21,0.11], ...
'fontsize' ,11,'string' , '返  回  目  录' , 'callback' , 'syxm' );

h_text=uicontrol(gcf, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.05,0.8,0.6,0.08], ...
'horizontal' , 'left' ,'fontsize' ,12,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9], 'string' ,{ '                连续函数x(t)与h(t)的卷积为' });
h_text=uicontrol(gcf, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.05,0.64,0.6,0.08], ...
'horizontal' , 'left' ,'fontsize' ,12,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9], 'string' ,{ '                若x(t)和h(t)分别仅在时间区间(t1，t2)和(t3，t4)有' });
h_text=uicontrol(gcf, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.05,0.56,0.6,0.08], ...
'horizontal' , 'left' ,'fontsize' ,12,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9], 'string' ,{ '        非零的值，则卷积y(t)=x(t)*h(t)有非零值的时间区间为' });
h_text=uicontrol(gcf, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.05,0.48,0.6,0.08], ...
'horizontal' , 'left' ,'fontsize' ,12,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9], 'string' ,{ '        (t1+t3，t2+t4)。 ' });
h_text=uicontrol(gcf, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.05,0.4,0.6,0.08], ...
'horizontal' , 'left' ,'fontsize' ,12,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9], 'string' ,{ '                在右侧的下拉框中选择信号类型，然后点击“开始' });
h_text=uicontrol(gcf, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.05,0.32,0.6,0.08], ...
'horizontal' , 'left' ,'fontsize' ,12,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9], 'string' ,{ '        仿真”按钮，即可得到相应信号的卷积；点击“返回目录 ' });
h_text=uicontrol(gcf, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.05,0.24,0.6,0.08], ...
'horizontal' , 'left' ,'fontsize' ,12,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9], 'string' ,{ '        ”按钮，回到目录界面，以便选择其它仿真。' });
h_text=uicontrol(gcf, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.05,0.16,0.6,0.08], ...
'horizontal' , 'left' ,'fontsize' ,12,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9], 'string' ,{ '                仿真过程中欲退出该软件可直接关闭窗口。 ' });

h3=axes('Position',[0.01,0.1,0.55,0.7]); % 设置画框图的轴位框 
set(h3,'Xlim',[0,1.2],'Ylim',[0,0.5]); % 设置轴的刻度范围 
set(h3,'DataAspectRatio',[1 1 1]); % 设置刻度比例 
set(h3,'ColorOrder',[0,0,0]); % 设置绘线的首选用色 
set(h3,'Visible','off'); % 隐去坐标轴
sint='{\fontsize{13}\int_{\fontsize{9}-∞}^{ ∞}}';
text(0.45,0.69,['\fontsize{12}y(t)=x(t)*h(t)=',sint,'\fontsize{12}x(\tau)h(t-\tau)d\tau'],'color','blue'); 