% Copyright (c) 1997-2000 by TH Technology, Inc.
% All Rights Reserved.
% Date: 2006/01/02
clear
clf reset
set(gcf, 'unit' , 'normalized' , 'position' ,[0.18,0.2,0.7,0.5]);
set(gcf, 'defaultuicontrolunits' , 'normalized' );
set(gcf, 'defaultuicontrolhorizontal' , 'left' );
str='连续信号';
set(gcf, 'name' ,str,'color',[0.7 0.7 0.9], 'numbertitle' , 'off' ); % 书写图形窗名
h_axes=axes( 'position' ,[0.08,0.15,0.53,0.75]); % 定义轴位框位置
xlabel('t(s)');ylabel('幅度(V)');grid on;
h_text=uicontrol(gcf,'Style','frame',...
'unit' , 'normalized' , 'backgroundcolor',[0.4 0.4 0.5], 'position' ,[0.63,0.11,0.356,0.79], ...
'horizontal' , 'left' ,'fontsize' ,11);
h_push1=uicontrol(gcf, 'style' , 'push' , ...
'unit' , 'normalized' ,'foregroundcolor','k','backgroundcolor',[0.3 0.8 0.6],'fontname',' 隶书' , 'position' ,[0.65,0.72,0.15,0.11], ...
'string' , '正 弦 信 号' ,'fontsize' ,11, 'callback' , 'xhsyhs2' );
h_push2=uicontrol(gcf, 'style' , 'push' , ...
'unit' , 'normalized' ,'foregroundcolor','k','backgroundcolor',[0.3 0.8 0.6],'fontname',' 隶书' , 'position' ,[0.82,0.72,0.15,0.11], ...
'string' , '矩形波信号' ,'fontsize' ,11, 'callback' , 'xhsyhs4' );
h_push3=uicontrol(gcf, 'style' , 'push' , ...
'unit' , 'normalized' , 'foregroundcolor','k','backgroundcolor',[0.3 0.8 0.6],'fontname',' 隶书' ,'position' ,[0.65,0.54,0.15,0.11], ...
'fontsize' ,11,'string' , '锯齿波信号' , ...
'callback' , 'xhsyhs10');
h_push4=uicontrol(gcf, 'style' , 'push' , ...
'unit' , 'normalized' ,'foregroundcolor','k', 'backgroundcolor',[0.3 0.8 0.6],'fontname',' 隶书' ,'position' ,[0.82,0.36,0.15,0.11], ...
'string' , '斜 坡 信 号' ,'fontsize' ,11, 'callback' , 'xhsyhs8' );
h_push5=uicontrol(gcf, 'style' , 'push' , ...
'unit' , 'normalized' ,'foregroundcolor','k', 'backgroundcolor',[0.3 0.8 0.6],'fontname',' 隶书' ,'position' ,[0.65,0.36,0.15,0.11], ...
'string' , '指数函数信号' ,'fontsize' ,11,'callback' , 'xhsyhs6');
h_push6=uicontrol(gcf, 'style' , 'push' , ...
'unit' , 'normalized' , 'foregroundcolor','k','backgroundcolor',[0.3 0.8 0.6],'fontname',' 隶书' ,'position' ,[0.82,0.54,0.15,0.11], ...
'fontsize' ,11,'string' , '阶 跃 信 号' , ...
'callback' , 'xhsyhs12');
h_push7=uicontrol(gcf, 'style' , 'push' , ...
'unit' , 'normalized' , 'foregroundcolor','k','backgroundcolor',[0.3 0.8 0.6],'fontname',' 隶书' ,'position' ,[0.65,0.18,0.15,0.11], ...
'fontsize' ,11,'string' , '抽样函数信号' , ...
'callback' , ['t=-3*pi:pi/100:3*pi;' , ...
'ft=sinc(t/pi);plot(t,ft); ' , ...
'xlabel(''t(s)'');ylabel(''幅度(V)'');title(''抽样函数信号'');grid on;']);
h_push8=uicontrol(gcf, 'style' , 'push' , ...
'unit' , 'normalized' , 'foregroundcolor','k','fontsize' ,11,'backgroundcolor',[0.9 0.7 0.6],'fontname',' 隶书' ,'position' ,[0.82,0.18,0.15,0.11], ...
'string' , '返 回 目 录' ,'callback' , 'syxm');