% Copyright (c) 1997-2000 by TH Technology, Inc.
% All Rights Reserved.
% Date: 2006/01/02
clear
clf reset
H=axes( 'unit' , 'normalized' , 'position' ,[0,0,1,1], 'visible' , 'off' );
set(gcf, 'currentaxes' ,H);
h_fig=get(H, 'parent' );
set(h_fig, 'unit' , 'normalized' ,'color',[0.2 0.4 0.7], 'position' ,[0.18,0.2,0.7,0.6]);
str= ' 信号与系统仿真软件 ' ;
set(gcf, 'name' ,str, 'numbertitle' , 'off' ); % 书写图形窗名
%h_text=uicontrol(h_fig, 'style' , 'text' , ...
%'unit' , 'normalized' , 'position' ,[0.04,0.85,0.2,0.05], ...
%'horizontal' , 'center' , 'fontsize' ,10,'fontname',' 隶书' ,'backgroundcolor',[0.2 0.4 0.7],'foregroundcolor','r','string' ,{ 'Signal & System' });
h_text=uicontrol(h_fig, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.1,0.62,0.82,0.15], ...
'horizontal' , 'center' , 'fontsize' ,40,'fontname',' 行书' ,'backgroundcolor',[0.2 0.4 0.7],'foregroundcolor','w','string' ,{ '信号与系统MATLAB仿真' });
h_text=uicontrol(h_fig, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.29,0.4,0.45,0.08], ...
'horizontal' , 'center' , 'fontsize' ,18,'fontname',' 隶书' ,'backgroundcolor',[0.2 0.4 0.7],'foregroundcolor','y','string' ,{ '浙江天煌科技实业有限公司' });
h_push=uicontrol(h_fig, 'style' , 'push' , ...
'unit' , 'normalized' ,'foregroundcolor','k', 'backgroundcolor',[0.9 0.6 0.5],'position' ,[0.23,0.15,0.1,0.08], ...
'fontsize' ,15,'fontangle','italic','string' , '简介' , 'callback' , 'jj' );
h_push=uicontrol(h_fig, 'style' , 'push' , ...
'unit' , 'normalized' ,'foregroundcolor','k','backgroundcolor',[0.9 0.6 0.5], 'position' ,[0.46,0.15,0.1,0.08], ...
'fontsize' ,15,'fontangle','italic','string' , '进入' , 'callback' , 'syxm' );
h_push=uicontrol(h_fig, 'style' , 'push' , ...
'unit' , 'normalized' ,'foregroundcolor','r','backgroundcolor',[0.9 0.6 0.5], 'position' ,[0.69,0.15,0.1,0.08], ...
'fontsize' ,15,'fontangle','italic','string' , '退出' , 'callback' , 'close' );

