% Copyright (c) 1997-2000 by TH Technology, Inc.
% All Rights Reserved.
% Date: 2006/01/02
clear
clf reset
set(gcf, 'unit' , 'normalized' , 'position' ,[0.18,0.2,0.6,0.5]);
set(gcf, 'defaultuicontrolunits' , 'normalized' );
set(gcf, 'defaultuicontrolfontsize' ,12);
set(gcf, 'defaultuicontrolfontname' , ' 隶书 ' );
set(gcf, 'defaultuicontrolhorizontal' , 'left' );
str= '周期信号的频谱表示 ' ;
set(gcf, 'name' ,str,'color',[0.7 0.7 0.9], 'numbertitle' , 'off' ); % 书写图形窗名
h_text=uicontrol(gcf,'Style','frame',...
'unit' , 'normalized' , 'backgroundcolor',[0.4 0.4 0.5], 'position' ,[0.7,0.11,0.28,0.79], ...
'horizontal' , 'left' ,'fontsize' ,11);
h_text=uicontrol(gcf, 'style' , 'text' , ...
'unit' , 'normalized' , 'HorizontalAlignment','left','position' ,[0.045,0.82,0.64,0.08], ...
'horizontal' , 'left' , 'fontsize' ,11,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9],'string' ,{'满足狄里赫利条件的周期信号f(t)的指数型傅立叶级数为'});
h_text=uicontrol(gcf, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.045,0.41,0.64,0.08], ...
'horizontal' , 'left' , 'fontsize' ,11,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9],'string' ,{'        点击右侧的按钮，可进入三种波形的仿真，进入所'});
h_text=uicontrol(gcf, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.045,0.34,0.64,0.08], ...
'horizontal' , 'left' , 'fontsize' ,11,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9],'string' ,{'选波形仿真页面后，在右侧的文本框中分别输入矩形波'});
h_text=uicontrol(gcf, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.045,0.27,0.64,0.08], ...
'horizontal' , 'left' , 'fontsize' ,11,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9],'string' ,{'周期(1-1000s之间)和正半周所占时间后，点击“开始仿'});
h_text=uicontrol(gcf, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.045,0.2,0.65,0.08], ...
'horizontal' , 'left' , 'fontsize' ,11,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9],'string' ,{'真”按钮，即可观察到波形及其频谱；点击“返回目录”按'});
h_text=uicontrol(gcf, 'style' , 'text' , ...
'unit' , 'normalized' , 'HorizontalAlignment','left','position' ,[0.045,0.13,0.64,0.08], ...
'horizontal' , 'left' , 'fontsize' ,11,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9],'string' ,{ '钮，回到目录界面，以便开始其它的仿真。'});
h_text=uicontrol(gcf, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.09,0.06,0.60,0.08], ...
'horizontal' , 'left' , 'fontsize' ,11,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9],'string' ,{'仿真过程中欲退出该软件可直接关闭窗口。'});

h_push=uicontrol(gcf, 'style' , 'push' , ...
'unit' , 'normalized' ,'fontsize' ,11,'foregroundcolor','k','backgroundcolor',[0.3 0.8 0.6],'fontname','行书',  'position' ,[0.732,0.54,0.22,0.1], ...
'string' , '周期矩形波频谱' , 'callback' , 'jxbpp ' );
h_push=uicontrol(gcf, 'style' , 'push' , ...
'unit' , 'normalized' ,'fontsize' ,11,'foregroundcolor','k','backgroundcolor',[0.3 0.8 0.6],'fontname','行书',  'position' ,[0.732,0.37,0.22,0.1], ...
'string' , '周期锯齿波频谱' , 'callback' , 'jcbpp' );
h_push=uicontrol(gcf, 'style' , 'push' , ...
'unit' , 'normalized' ,'fontsize' ,11,'foregroundcolor','k','backgroundcolor',[0.3 0.8 0.6],'fontname','行书',  'position' ,[0.732,0.71,0.22,0.1], ...
'string' , '周期正弦波频谱' , 'callback' , 'zxbpp' );

h_push=uicontrol(gcf, 'style' , 'push' , ...
'unit' , 'normalized' ,'fontsize' ,11,'foregroundcolor','k','backgroundcolor',[0.9 0.7 0.6],'fontname','行书',  'position' ,[0.732,0.2,0.22,0.1], ...
'string' , '返  回  目  录' , 'callback' , 'syxm' );
h3=axes('Position',[0.01,0.1,0.55,0.7]); % 设置画框图的轴位框 
set(h3,'Xlim',[0,1.2],'Ylim',[0,0.5]); % 设置轴的刻度范围 
set(h3,'DataAspectRatio',[1 1 1]); % 设置刻度比例 
set(h3,'ColorOrder',[0,0,0]); % 设置绘线的首选用色 
set(h3,'Visible','off'); % 隐去坐标轴
sint='{\fontsize{13}∑_{\fontsize{8}n=1}^{\fontsize{9} ∞}}';
text(0.3,0.72,['\fontsize{11}f(t)=F_0+',sint,'\fontsize{12}F_ne^j^n^ω^0^t+',sint,'\fontsize{12}F_n^*e^-^j^n^ω^0^t'],'color','blue');
text(0.18,0.61,['\fontsize{11}当f(t)\rm为实信号时，则'],'color','blue');
sint='{\fontsize{13}∑_{\fontsize{8}n= -∞}^{\fontsize{9}  ∞}}';
text(0.6,0.51,['\fontsize{11}f(t)=',sint,'F_ne^j^n^ω^0^t'],'color','blue');
sint1='{\fontsize{13}\int_{\fontsize{8}-0.5T}^{\fontsize{8} 0.5T}}';
text(0.18,0.39,['\fontsize{11}其中：F_n=',sint1,'\fontsize{12}f(t)e^-^j^n^ω^0^tdt/T    \rmn=0，±1，±2,……'],'color','blue');

