% Copyright (c) 1997-2000 by TH Technology, Inc.
% All Rights Reserved.
% Date: 2006/01/02
clear
clf reset
set(gcf, 'unit' , 'normalized' , 'position' ,[0.18,0.2,0.6,0.5]);
set(gcf, 'defaultuicontrolunits' , 'normalized' );
set(gcf, 'defaultuicontrolfontsize' ,12);
set(gcf, 'defaultuicontrolfontname' , ' 隶书 ' );
set(gcf, 'defaultuicontrolhorizontal' , 'left' );
str= '周期信号的频谱表示 ' ;
set(gcf, 'name' ,str,'color',[0.7 0.7 0.9], 'numbertitle' , 'off' ); % 书写图形窗名

h_text=uicontrol(gcf,'Style','frame',...
'unit' , 'normalized' , 'backgroundcolor',[0.4 0.4 0.5], 'position' ,[0.695,0.10,0.273,0.79], ...
'horizontal' , 'left' ,'fontsize' ,11);


h_text=uicontrol(gcf, 'style' , 'text' , ...
'unit' , 'normalized' , 'HorizontalAlignment','left','position' ,[0.045,0.82,0.64,0.08], ...
'horizontal' , 'left' , 'fontsize' ,11,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9],'string' ,{'满足狄里赫利条件的周期信号f(t)的指数型傅立叶级数为'});
h_text=uicontrol(gcf, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.045,0.34,0.64,0.08], ...
'horizontal' , 'left' , 'fontsize' ,11,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9],'string' ,{'        在右侧的文本框中分别输入矩形波周期(0.1-1000s之'});
h_text=uicontrol(gcf, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.045,0.27,0.64,0.08], ...
'horizontal' , 'left' , 'fontsize' ,11,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9],'string' ,{'间)和正半周所占时间后，点击“开始仿真”按钮，即可观'});
h_text=uicontrol(gcf, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.045,0.2,0.65,0.08], ...
'horizontal' , 'left' , 'fontsize' ,11,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9],'string' ,{'察到矩形波及其频谱；点击“返回目录”按钮，回到目录界'});
h_text=uicontrol(gcf, 'style' , 'text' , ...
'unit' , 'normalized' , 'HorizontalAlignment','left','position' ,[0.045,0.13,0.64,0.08], ...
'horizontal' , 'left' , 'fontsize' ,11,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9],'string' ,{ '面，以便开始其它的仿真。'});
h_text=uicontrol(gcf, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.09,0.06,0.60,0.08], ...
'horizontal' , 'left' , 'fontsize' ,11,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9],'string' ,{'仿真过程中欲退出该软件可直接关闭窗口。'});

h_text=uicontrol(gcf, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.72,0.74,0.22,0.12], ...
'horizontal' , 'left' ,'fontsize' ,9,'foregroundcolor','k','backgroundcolor',[0.7 0.7 0.9], 'string' ,{ '矩形波周期(单位:s)' });
h_edit=uicontrol(gcf, 'style' , 'edit' , ...
'unit' , 'normalized' ,'fontname',' 隶书' ,'fontsize' ,10,'foregroundcolor','k','backgroundcolor','w', 'position' ,[0.72,0.735,0.22,0.08], ...
'horizontal' , 'left' , ...
'callback' ,['T=str2num(get(gcbo,''string''));']);

h_text=uicontrol(gcf, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.72,0.55,0.22,0.12], ...
'horizontal' , 'left' ,'fontsize' ,9,'foregroundcolor','k','backgroundcolor',[0.7 0.7 0.9], 'string' ,{ '正半周时间(单位:s)' });
h_edit=uicontrol(gcf, 'style' , 'edit' , ...
'unit' , 'normalized' ,'fontname',' 行书' ,'fontsize' ,10,'foregroundcolor','k','backgroundcolor','w', 'position' ,[0.72,0.545,0.22,0.08], ...
'horizontal' , 'left' , ...
'callback' ,['w=str2num(get(gcbo,''string''));']);

h_push=uicontrol(gcf, 'style' , 'push' , ...
'unit' , 'normalized' ,'fontsize' ,11,'foregroundcolor','k','backgroundcolor',[0.7 0.7 0.9], 'position' ,[0.72,0.3,0.22,0.1], ...
'string' , '开  始  仿  真' , 'callback' , 'Flyppt(T,w) ' );

h_push=uicontrol(gcf, 'style' , 'push' , ...
'unit' , 'normalized' ,'fontsize' ,11,'foregroundcolor','k','backgroundcolor',[0.7 0.7 0.9], 'position' ,[0.72,0.13,0.22,0.1], ...
'string' , '返  回  目  录' , 'callback' , 'syxm' );
h3=axes('Position',[0.01,0.1,0.55,0.7]); % 设置画框图的轴位框 
set(h3,'Xlim',[0,1.2],'Ylim',[0,0.5]); % 设置轴的刻度范围 
set(h3,'DataAspectRatio',[1 1 1]); % 设置刻度比例 
set(h3,'ColorOrder',[0,0,0]); % 设置绘线的首选用色 
set(h3,'Visible','off'); % 隐去坐标轴
sint='{\fontsize{13}∑_{\fontsize{8}n=1}^{\fontsize{9} ∞}}';
text(0.3,0.72,['\fontsize{12}f(t)=F_0+',sint,'\fontsize{12}F_ne^j^n^ω^0^t+',sint,'\fontsize{12}F_n^*e^-^j^n^ω^0^t'],'color','blue');
text(0.18,0.58,['\fontsize{12}当f(t)\rm为实信号时，则'],'color','blue');
sint='{\fontsize{13}∑_{\fontsize{8}n= -∞}^{\fontsize{9}  ∞}}';
text(0.6,0.46,['\fontsize{12}f(t)=',sint,'F_ne^j^n^ω^0^t'],'color','blue');
sint1='{\fontsize{13}\int_{\fontsize{8}-0.5T}^{\fontsize{8} 0.5T}}';
text(0.18,0.3,['\fontsize{12}其中：F_n=',sint1,'\fontsize{12}f(t)e^-^j^n^ω^0^tdt/T    \rmn=0，±1，±2,……'],'color','blue');
