# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'serverui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_serverui(object):
    def setupUi(self, serverui):
        serverui.setObjectName("serverui")
        serverui.resize(500, 400)
        self.label = QtWidgets.QLabel(serverui)
        self.label.setGeometry(QtCore.QRect(30, 20, 100, 30))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(serverui)
        self.lineEdit.setGeometry(QtCore.QRect(140, 20, 250, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.table = QtWidgets.QTableWidget(serverui)
        self.table.setGeometry(QtCore.QRect(20, 80, 450, 240))
        self.table.setObjectName("table")
        self.table.setColumnCount(3)
        self.table.setHorizontalHeaderLabels(["时间","IP","信息内容"])

        self.pushButton = QtWidgets.QPushButton(serverui)
        self.pushButton.setGeometry(QtCore.QRect(40, 350, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(serverui)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 350, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(serverui)
        self.pushButton_3.setGeometry(QtCore.QRect(330, 350, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(serverui)
        QtCore.QMetaObject.connectSlotsByName(serverui)

    def retranslateUi(self, serverui):
        _translate = QtCore.QCoreApplication.translate
        serverui.setWindowTitle(_translate("serverui", "2019217864服务器"))
        self.label.setText(_translate("serverui", "本机IP地址"))
        # self.table.setTitle(_translate("serverui", "数据显示区"))
        self.pushButton.setText(_translate("serverui", "启动服务"))
        self.pushButton_2.setText(_translate("serverui", "停止服务"))
        self.pushButton_3.setText(_translate("serverui", "退出"))

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_serverui()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())