% Copyright (c) 1997-2000 by TH Technology, Inc.
% All Rights Reserved.
% Date: 2006/01/02
clear
clf reset
str= ' 信号的采样与恢复 ' ;
set(gcf, 'name' ,str,'unit' , 'normalized' , 'color',[0.7 0.7 0.9],'numbertitle' , 'off','position' ,[0.18,0.2,0.7,0.5] ); % 书写图形窗名

h_text=uicontrol(gcf,'Style','frame',...
'unit' , 'normalized' , 'backgroundcolor',[0.4 0.4 0.5], 'position' ,[0.671,0.09,0.305,0.82], ...
'horizontal' , 'left' ,'fontsize' ,11);

h_push1=uicontrol(gcf, 'style' , 'push' , ...
'unit' , 'normalized' ,'fontname',' 行书' , 'backgroundcolor',[0.3 0.8 0.6],'position' ,[0.7,0.75,0.25,0.12], ...
'foregroundcolor','k','fontsize' ,12,'string' , '原信号时域图及频谱图' , ...
'callback' ,'cyhf1');
h_text=uicontrol(gcf, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.7,0.6,0.25,0.06], ...
'horizontal' , 'left' ,'fontsize' ,11,'foregroundcolor','k','backgroundcolor',[0.3 0.8 0.6], 'string' ,{ ' 采样频率 fs =' });
h_edit=uicontrol(gcf, 'style' , 'edit' , ...
'unit' , 'normalized' ,'foregroundcolor','k','backgroundcolor','w', 'position' ,[0.7,0.52,0.25,0.09], ...
'fontsize' ,12,'horizontal' , 'left' , ...
'callback' ,[ ...
'fs=str2num(get(gcbo,''string''));']);
 
h_push5=uicontrol(gcf, 'style' , 'push' , ...
'unit' , 'normalized' ,'fontname',' 行书' ,'fontsize' ,12, 'backgroundcolor',[0.3 0.8 0.6],'position' ,[0.7,0.32,0.25,0.12], ...
'string' , '采 样 及 恢 复 信 号' ,'foregroundcolor','k', 'callback' , [...
't=0:0.001:3;' , ... %离散时间信号
'xa=sin(2*pi*t);', ...
'Ts=1/fs;n=0:1:300;', ...
'x=sin(0.1+2*pi*(n*Ts));', ...%离散傅里叶变换
'K=5000;k=0:1:K;', ...
'w=pi*k/K;', ...
'X=x*exp(-j*n''*w);', ...
'X=real(X);', ...
'w=[-fliplr(w),w(2:K+1)];', ...
'X=[fliplr(X),X(2:K+1)];', ...
'xt=spline(n*Ts,x,t);', ...%模拟信号重建（使用立方体三次样条函数spline）
'error1=max(abs(xt-sin(2*pi*t)));', ...
'figure(3);', ...
'subplot(2,1,1);plot(t,xa);ylabel(''x_1'');grid on;', ...
'title(''原信号及离散信号'');hold on;stem(n*Ts,x,''r'');legend(''原信号'',''离散信号'');hold off;axis([0 3 -1 1]);'...
'subplot(2,1,2);plot(t,xa,t,xt,''r''); legend(''原信号'',''恢复信号'');xlabel(''t(s)'');ylabel(''x_a_1(t) '');title(''原信号及重建信号 '');grid on;']);

h_push5=uicontrol(gcf, 'style' , 'push' , ...
'unit' , 'normalized' ,'fontname',' 行书' ,'fontsize' ,12, 'backgroundcolor',[0.9 0.7 0.6],'position' ,[0.7,0.13,0.25,0.12], ...
'string' , '返   回   目   录' ,'foregroundcolor','k', 'callback' , 'syxm' );

h3=axes('Position',[0.01,0.01,0.55,0.9]); % 设置画框图的轴位框 
set(h3,'Xlim',[0,1.2],'Ylim',[0,0.7]); % 设置轴的刻度范围 
set(h3,'DataAspectRatio',[1 1 1]); % 设置刻度比例 
set(h3,'ColorOrder',[0,0,0]); % 设置绘线的首选用色 
set(h3,'Visible','off'); % 隐去坐标轴
text(0.2,0.85,['\fontsize{12}为使采样信号\itf_s(t)\rm的频谱中完整地保留原信号\itf(t)\rm的频谱，'],'color','blue');
text(0.1,0.77,['\fontsize{12}应满足下列两个条件：'],'color','blue');
text(0.2,0.69,['\fontsize{12}(1)   \itf(t)\rm必须是带限信号，即在\it|ω|>ω_m\rm时，其频谱\itF(ω)=0\rm；'],'color','blue');
text(0.2,0.61,['\fontsize{12}(2)   取样的频率不能过低，必须满足\itf_s≥2f_m\rm即(\itω_s≥2ω_m\rm)。'],'color','blue');
text(0.2,0.53,['\fontsize{12}本次仿真采用的信号为：'],'color','blue');
text(0.65,0.46,['\fontsize{12}\itf(t)=sin(2πt)'],'color','blue');
text(0.2,0.37,['\fontsize{12}点击右侧的“原信号时域图及频谱图”按钮，得到仿真信号'],'color','blue');
text(0.1,0.29,['\fontsize{12}的波形及其频谱图；在文本框中输入0.5—100Hz之间的采样'],'color','blue');
text(0.1,0.21,['\fontsize{12}频率，并点击“采样及恢复信号”按钮，得到不同采样频率下的'],'color','blue');
text(0.1,0.13,['\fontsize{12}采样信号及恢复信号；点击“返回目录”按钮，回到目录界面，'],'color','blue');
text(0.1,0.05,['\fontsize{12}以便开始其它仿真。'],'color','blue');
text(0.2,-0.03,['\fontsize{12}仿真过程中欲退出该软件可直接关闭窗口。'],'color','blue');