% Copyright (c) 1997-2000 by TH Technology, Inc.
% All Rights Reserved.
% Date: 2006/01/02
clear
clf reset
H=axes( 'unit' , 'normalized' , 'position' ,[0,0,1,1], 'visible' , 'off' );
set(gcf, 'currentaxes' ,H);
h_fig=get(H, 'parent' );
set(h_fig, 'menubar','none','unit' , 'normalized' , 'color',[0.7 0.7 0.7],'position' ,[0.18,0.2,0.6,0.5]);
str= ' 信号与系统及仿真软件简介 ' ;
set(gcf, 'name' ,str,'color',[0.7 0.7 0.9], 'numbertitle' , 'off' ); % 书写图形窗名
h_text=uicontrol(h_fig, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.45,0.82,0.3,0.08], ...
'horizontal' , 'left' , 'fontsize' ,15,'fontname',' 隶书' ,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9],'string' ,{ '简     介' });
h_text=uicontrol(h_fig, 'style' , 'text' , ...
'unit' , 'normalized' , 'HorizontalAlignment','left','position' ,[0.14,0.74,0.85,0.05], ...
'horizontal' , 'left' , 'fontsize' ,12,'fontname',' 隶书' ,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9],'string' ,{ '       “信号与系统”课程是工科大学电气与信息类相关专业的一门'});
h_text=uicontrol(h_fig, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.14,0.66,0.85,0.05], ...
'horizontal' , 'left' , 'fontsize' ,12,'fontname',' 隶书' ,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9],'string' ,{'专业基础课，它的基本概念和分析处理问题的方法对学生学习本'});
h_text=uicontrol(h_fig, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.14,0.58,0.85,0.05], ...
'horizontal' , 'left' , 'fontsize' ,12,'fontname',' 隶书' ,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9],'string' ,{'专业的后续课程是十分有用的。'});
h_text=uicontrol(h_fig, 'style' , 'text' , ...
'unit' , 'normalized' , 'HorizontalAlignment','left','position' ,[0.14,0.5,0.85,0.05], ...
'horizontal' , 'left' , 'fontsize' ,12,'fontname',' 隶书' ,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9],'string' ,{'        为帮助学生学好该课程，我公司在MATLAB平台上开发了“信'});
h_text=uicontrol(h_fig, 'style' , 'text' , ...
'unit' , 'normalized' , 'HorizontalAlignment','left','position' ,[0.14,0.42,0.85,0.05], ...
'horizontal' , 'left' , 'fontsize' ,12,'fontname',' 隶书' ,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9],'string' ,{'号与系统”十三个仿真实验。利用MATLAB仿真软件能方便地调节'});
h_text=uicontrol(h_fig, 'style' , 'text' , ...
'unit' , 'normalized' , 'HorizontalAlignment','left','position' ,[0.14,0.34,0.85,0.05], ...
'horizontal' , 'left' , 'fontsize' ,12,'fontname',' 隶书' ,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9],'string' ,{ '相关的实验参数，验证预测结果，从而大大节省了工程设计的时'});
h_text=uicontrol(h_fig, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.14,0.26,0.85,0.05], ...
'horizontal' , 'left' , 'fontsize' ,12,'fontname',' 隶书' ,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9],'string' ,{'间，缩短了产品的开发周期。'});

h_push=uicontrol(h_fig, 'style' , 'push' , ...
'unit' , 'normalized' ,'fontname','行书' ,'foregroundcolor','blue', 'backgroundcolor',[0.7 0.7 0.9],'position' ,[0.72,0.08,0.15,0.1], ...
'fontsize' ,12,'string' , '返   回' , 'callback' , 'xhxtsy' );