% Copyright (c) 1997-2000 by TH Technology, Inc.
% All Rights Reserved.
% Date: 2006/01/02
clear
clf reset
set(gcf, 'unit' , 'normalized' , 'position' ,[0.18,0.15,0.72,0.65]);
set(gcf, 'defaultuicontrolunits' , 'normalized' );
set(gcf, 'defaultuicontrolfontsize' ,12);
set(gcf, 'defaultuicontrolfontname' , ' 隶书 ' );
set(gcf, 'defaultuicontrolhorizontal' , 'left' );
str= '周期矩形波信号的频谱表示 ' ;
set(gcf, 'name' ,str,'color',[0.7 0.7 0.9], 'numbertitle' , 'off' ); % 书写图形窗名
h_axes=axes( 'position' ,[0.08,0.56,0.58,0.38]);xlabel('t(s)');ylabel('幅度(V)');grid on; % 定义轴位框位置
h_axes1=axes( 'position' ,[0.08,0.075,0.58,0.38]);xlabel('t(s)');ylabel('幅度(V)');grid on; % 定义轴位框位置
h_text=uicontrol(gcf,'Style','frame', ...
'unit' , 'normalized' ,'backgroundcolor',[0.4 0.4 0.5], 'position' ,[0.715,0.074,0.25,0.865], ...
'horizontal' , 'left' ,'fontsize' ,11);

h_text=uicontrol(gcf, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.74,0.75,0.2,0.10], ...
'horizontal' , 'left' ,'fontsize' ,11,'backgroundcolor',[0.3 0.8 0.6], 'string' ,{ '矩形波周期(单位:s)' });
h_edit=uicontrol(gcf, 'style' , 'edit' , ...
'unit' , 'normalized' ,'fontsize' ,10,'foregroundcolor','k','backgroundcolor','w','fontname','行书', 'position' ,[0.74,0.75,0.2,0.07], ...
'horizontal' , 'left' , ...
'callback' ,['T=str2num(get(gcbo,''string''));']);

h_text=uicontrol(gcf, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.74,0.56,0.2,0.10], ...
'horizontal' , 'left' ,'fontsize' ,11,'backgroundcolor',[0.3 0.8 0.6], 'string' ,{ '正半周时间(单位:s)' });
h_edit=uicontrol(gcf, 'style' , 'edit' , ...
'unit' , 'normalized' ,'fontsize' ,10,'foregroundcolor','k','backgroundcolor','w','fontname','行书', 'position' ,[0.74,0.56,0.2,0.07], ...
'horizontal' , 'left' , ...
'callback' ,['w=str2num(get(gcbo,''string''));']);

h_push=uicontrol(gcf, 'style' , 'push' , ...
'unit' , 'normalized' ,'fontsize' ,12,'foregroundcolor','k','backgroundcolor',[0.3 0.8 0.6], 'position' ,[0.74,0.35,0.2,0.1], ...
'string' , '开  始  仿  真' , 'callback' , 'Flyppt(T,w,h_axes,h_axes1) ' );

h_push=uicontrol(gcf, 'style' , 'push' , ...
'unit' , 'normalized' ,'fontsize' ,12,'foregroundcolor','k','backgroundcolor',[0.9 0.7 0.6], 'position' ,[0.74,0.16,0.2,0.1], ...
'string' , '返  回  上  一  页' , 'callback' , 'zqxhpp' );

