% Copyright (c) 1997-2000 by TH Technology, Inc.
% All Rights Reserved.
% Date: 2006/01/02
clear
clf reset
str= ' LTI系统的频率响应 ' ;
set(gcf,'name' ,str,'unit' , 'normalized' , 'color',[0.7 0.7 0.9],'numbertitle' , 'off','position' ,[0.18,0.2,0.68,0.5] ); % 书写图形窗名

h_text=uicontrol(gcf,'Style','frame',...
'unit' , 'normalized' , 'backgroundcolor',[0.4 0.4 0.5], 'position' ,[0.675,0.08,0.30,0.87], ...
'horizontal' , 'left' ,'fontsize' ,11);

h_push5=uicontrol(gcf, 'style' , 'push' , ...
'unit' , 'normalized' ,'fontname','行书','fontsize' ,13, 'backgroundcolor',[0.9 0.7 0.6],'position' ,[0.7,0.11,0.25,0.11], ...
'string' , '返  回  目  录' ,'foregroundcolor','k', 'callback' , 'syxm' );
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
h_text=uicontrol(gcf, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.7,0.86,0.25,0.06], ...
'horizontal' , 'left' ,'fontsize' ,12,'foregroundcolor','k','backgroundcolor',[0.3 0.8 0.6], 'string' ,{ 'a  取值为：' });

h_text=uicontrol(gcf, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.715,0.84,0.006,0.06], ...
'horizontal' , 'left' ,'fontname','行书','fontsize' ,7,'foregroundcolor','k','backgroundcolor',[0.3 0.8 0.6], 'string' ,{ 'i' });

h_edit=uicontrol(gcf, 'style' , 'edit' , ...
'unit' , 'normalized' ,'foregroundcolor','k','backgroundcolor','w', 'position' ,[0.7,0.8,0.25,0.07], ...
'fontsize' ,12,'horizontal' , 'left' , ...
'callback' ,[ ...
'a=str2num(get(gcbo,''string''));']);

h_text=uicontrol(gcf, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.7,0.70,0.25,0.06], ...
'horizontal' , 'left' ,'fontsize' ,12,'foregroundcolor','k','backgroundcolor',[0.3 0.8 0.6], 'string' ,{ 'b  取值为：' });

h_text=uicontrol(gcf, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.715,0.68,0.006,0.06], ...
'horizontal' , 'left' ,'fontname','行书','fontsize' ,7,'foregroundcolor','k','backgroundcolor',[0.3 0.8 0.6], 'string' ,{ 'i' });

h_edit=uicontrol(gcf, 'style' , 'edit' , ...
'unit' , 'normalized' ,'foregroundcolor','k','backgroundcolor','w', 'position' ,[0.7,0.64,0.25,0.07], ...
'fontsize' ,12,'horizontal' , 'left' , ...
'callback' ,[ ...
'b=str2num(get(gcbo,''string''));']);

h_push5=uicontrol(gcf, 'style' , 'push' , ...
'unit' , 'normalized' ,'fontname','行书','fontsize' ,13, 'backgroundcolor',[0.3 0.8 0.6],'position' ,[0.7,0.47,0.25,0.11], ...
'string' , '系统Bode图' ,'foregroundcolor','k', 'callback' , [...
'num=[a];', ...
'den=[b];', ...
'sys=tf(num,den);', ...
'figure(3);', ...
'bode(sys);grid on;']);


h_push5=uicontrol(gcf, 'style' , 'push' , ...
'unit' , 'normalized' ,'fontname','行书','fontsize' ,13, 'backgroundcolor',[0.3 0.8 0.6],'position' ,[0.7,0.29,0.25,0.11], ...
'string' , '系统Nyquist图' ,'foregroundcolor','k', 'callback' ,[...
'num=[a];', ...
'den=[b];', ...
'sys=tf(num,den);', ...
'figure(3);', ...
'nyquist(sys);grid on;']);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
h3=axes('Position',[0.05,0.08,0.6,0.85]); % 设置画框图的轴位框 
set(h3,'Xlim',[0,1.2],'Ylim',[0,0.9]); % 设置轴的刻度范围 
set(h3,'DataAspectRatio',[1 1 1]); % 设置刻度比例 
set(h3,'ColorOrder',[0,0,0]); % 设置绘线的首选用色 
set(h3,'Visible','off'); % 隐去坐标轴

%text(1.3,0.89,['\fontsize{12}a_i'],'color','blue');% 输入文本框上...
%text(1.3,0.71,['\fontsize{12}b_j'],'color','blue');% 输入文本框上...

text(0.09,0.8,['\fontsize{12}a_0'],'color','blue');
text(0.15,0.84,'d^n','fontsize' ,11,'hor','left','color','blue');
xx7=0.14:0.01:0.21;yy7=0.80*ones(size(xx7));line(xx7,yy7,'color','blue');
text(0.15,0.77,'dt^n ','fontsize' ,11,'hor','left','color','blue');
text(0.21,0.8,['\fontsize{12}x_o(t)'],'color','blue');

text(0.29,0.80,['\fontsize{12}+a_1'],'color','blue');
text(0.36,0.84,'d^n^-^1','fontsize' ,11,'hor','left','color','blue');
xx7=0.36:0.01:0.44;yy7=0.80*ones(size(xx7));line(xx7,yy7,'color','blue');
text(0.36,0.77,'dt^n^-^1 ','fontsize' ,11,'hor','left','color','blue');
text(0.45,0.80,['\fontsize{12}x_o(t)+ ... +a_nx_o(t) = b_0'],'color','blue');

text(0.80,0.84,'d^m','fontsize' ,11,'hor','left','color','blue');
xx7=0.79:0.01:0.88;yy7=0.80*ones(size(xx7));line(xx7,yy7,'color','blue');
text(0.80,0.77,'dt^m ','fontsize' ,11,'hor','left','color','blue');
text(0.88,0.8,['\fontsize{12}x_i(t)+b_1'],'color','blue');

text(1.02,0.84,'d^m^-^1','fontsize' ,11,'hor','left','color','blue');
xx7=1.02:0.01:1.10;yy7=0.80*ones(size(xx7));line(xx7,yy7,'color','blue');
text(1.02,0.77,'dt^m^-^1 ','fontsize' ,11,'hor','left','color','blue');

text(0,0.69,['\fontsize{12}x_i(t)+ ... +b_mx_i(t)'],'color','blue');
text(0.09,0.61,['\fontsize{12}式中：x_o(t)为输入量'],'color','blue');
text(0.09,0.54,['\fontsize{12}            x_i (t)为输出量'],'color','blue');
text(0.0,0.9,['\fontsize{12}LT I系统模型为:'],'color','blue');
text(0.09,0.47,['\fontsize{12}在右侧的空白文本框中分别输入相应的a_i和b_j值，然后'],'color','blue');
text(0,0.4,['\fontsize{12}点击右侧的“系统Bode图”和“系统Nyquist图”按钮，可分别得'],'color','blue');
text(0,0.33,['\fontsize{12}到系统相应的Bode图仿真信号和Nyquist图仿真信号。通过'],'color','blue');
text(0,0.26,['\fontsize{12}对系统的Bode图、Nyquist图的观察分析LT I系统的频率响'],'color','blue');
text(0,0.19,['\fontsize{12}应。'],'color','blue');
text(0.09,0.12,['\fontsize{12}点击“返回目录”按钮，回到目录界面，以便开始其它仿'],'color','blue');
text(0,0.05,['\fontsize{12}真。仿真过程中欲退出该软件可直接关闭窗口。'],'color','blue');

