% Copyright (c) 1997-2000 by TH Technology, Inc.
% All Rights Reserved.
% Date: 2006/01/02
clear
clf reset
H=axes( 'unit' , 'normalized' , 'position' ,[0,0,1,1], 'visible' , 'off' );
set(gcf, 'currentaxes' ,H);
h_fig=get(H, 'parent' );
set(h_fig, 'unit' , 'normalized' , 'color',[0.7 0.7 0.7],'position' ,[0.18,0.2,0.7,0.6]);
str= ' 信号与系统仿真软件 ' ;
set(gcf, 'name' ,str, 'color',[0.7 0.7 0.9],'numbertitle' , 'off' ); % 书写图形窗名
h_text=uicontrol(h_fig, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.32,0.87,0.35,0.08], ...
'horizontal' , 'left' , 'fontsize' ,25,'foregroundcolor','red','backgroundcolor',[0.7 0.7 0.9],'fontname',' 楷书' ,'string' ,{ ' 仿真内容选择' });

h_push1=uicontrol(h_fig, 'style' , 'push' , ...
'unit' , 'normalized' ,'backgroundcolor',[0.7 0.7 0.9], 'position' ,[0.07,0.74,0.12,0.08], ...
'string' , '仿 真 一' ,'fontname','行书','fontsize',12 ,'callback' , 'xhsyhs1' );
h_text=uicontrol(h_fig, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.2,0.74,0.26,0.06], ...
'horizontal' , 'left' , 'fontsize' ,12,'fontname',' 隶书' ,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9],'string' ,{ ' 信号的时域表示' });

h_push10=uicontrol(h_fig, 'style' , 'push' , ...
'unit' , 'normalized' , 'position' ,[0.07,0.63,0.12,0.08], ...
'string' , '仿 真 二' ,'backgroundcolor',[0.7 0.7 0.9],'fontname','行书','fontsize',12 , 'callback' , 'xhjbys' );
h_text=uicontrol(h_fig, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.2,0.63,0.36,0.06], ...
'horizontal' , 'left' , 'fontsize' ,12,'fontname',' 隶书' ,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9],'string' ,{ ' 信号的基本运算' });

h_push2=uicontrol(h_fig, 'style' , 'push' , ...
'unit' , 'normalized' , 'position' ,[0.07,0.52,0.12,0.08], ...
'string' , '仿 真 三' ,'backgroundcolor',[0.7 0.7 0.9],'fontname','行书','fontsize',12 , 'callback' , 'lxxtxy' );
h_text=uicontrol(h_fig, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.2,0.52,0.5,0.06], ...
'horizontal' , 'left' , 'fontsize' ,12,'fontname',' 隶书' ,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9],'string' ,{ ' 连续时间系统的冲激响应和单位阶跃响应' });

h_push13=uicontrol(h_fig, 'style' , 'push' , ...
'unit' , 'normalized' , 'position' ,[0.07,0.41,0.12,0.08], ...
'string' , '仿 真 四' ,'backgroundcolor',[0.7 0.7 0.9],'fontname','行书','fontsize',12 , 'callback' , 'ejxtmn' );
h_text=uicontrol(h_fig, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.2,0.41,0.36,0.06], ...
'horizontal' , 'left' , 'fontsize' ,12,'fontname',' 隶书' ,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9],'string' ,{ ' 二阶系统的模拟' });

h_push3=uicontrol(h_fig, 'style' , 'push' , ...
'unit' , 'normalized' , 'position' ,[0.07,0.30,0.12,0.08], ...
'string' , '仿 真 五' ,'backgroundcolor',[0.7 0.7 0.9],'fontname','行书','fontsize',12 , 'callback' , 'lztxy' );
h_text=uicontrol(h_fig, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.2,0.30,0.5,0.06], ...
'horizontal' , 'left' , 'fontsize' ,12,'fontname',' 隶书' ,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9],'string' ,{ ' 系统的零输入、零状态及完全响应' });

h_push12=uicontrol(h_fig, 'style' , 'push' , ...
'unit' , 'normalized' , 'position' ,[0.07,0.19,0.12,0.08], ...
'string' , '仿 真 六' ,'backgroundcolor',[0.7 0.7 0.9],'fontname','行书','fontsize',12 , 'callback' , 'xtwdxfx' );
h_text=uicontrol(h_fig, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.2,0.19,0.36,0.06], ...
'horizontal' , 'left' , 'fontsize' ,12,'fontname',' 隶书' ,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9],'string' ,{ ' 线性系统的稳定性分析' });

h_push11=uicontrol(h_fig, 'style' , 'push' , ...
'unit' , 'normalized' , 'position' ,[0.07,0.08,0.12,0.08], ...
'string' , '仿 真 七' ,'backgroundcolor',[0.7 0.7 0.9],'fontname','行书','fontsize',12 , 'callback' , 'xhwszcs' );
h_text=uicontrol(h_fig, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.2,0.08,0.36,0.06], ...
'horizontal' , 'left' , 'fontsize' ,12,'fontname',' 隶书' ,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9],'string' ,{ ' 信号的无失真传输' });

h_push6=uicontrol(h_fig, 'style' , 'push' , ...
'unit' , 'normalized' , 'position' ,[0.62,0.74,0.12,0.08], ...
'string' , '仿 真 八' ,'backgroundcolor',[0.7 0.7 0.9],'fontname','行书','fontsize',12 , 'callback' , 'cyhf' );
h_text=uicontrol(h_fig, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.75,0.74,0.24,0.06], ...
'horizontal' , 'left' , 'fontsize' ,12,'fontname',' 隶书' ,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9],'string' ,{ ' 信号的采样与恢复' });

h_push7=uicontrol(h_fig, 'style' , 'push' , ...
'unit' , 'normalized' , 'position' ,[0.62,0.63,0.12,0.08], ...
'string' , '仿 真 九' ,'backgroundcolor',[0.7 0.7 0.9], 'fontname','行书','fontsize',12 ,'callback' , 'zftz' );
h_text=uicontrol(h_fig, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.75,0.63,0.24,0.06], ...
'horizontal' , 'left' , 'fontsize' ,12,'fontname',' 隶书' ,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9],'string' ,{ ' 幅度调制与解调' });

h_push8=uicontrol(h_fig, 'style' , 'push' , ...
'unit' , 'normalized' , 'position' ,[0.62,0.52,0.12,0.08], ...
'string' , '仿 真 十' ,'backgroundcolor',[0.7 0.7 0.9],'fontname','行书','fontsize',12 , 'callback' , 'lbqtxsy' );
h_text=uicontrol(h_fig, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.75,0.52,0.46,0.06], ...
'horizontal' , 'left' , 'fontsize' ,12,'fontname',' 隶书' ,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9],'string' ,{ ' 滤波器频率特性的研究' });

h_push9=uicontrol(h_fig, 'style' , 'push' , ...
'unit' , 'normalized' , 'position' ,[0.62,0.41,0.12,0.08], ...
'string' , '仿 真 十 一' ,'backgroundcolor',[0.7 0.7 0.9],'fontname','行书','fontsize',12 , 'callback' , 'xhfjhc' );
h_text=uicontrol(h_fig, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.75,0.41,0.36,0.06], ...
'horizontal' , 'left' , 'fontsize' ,12,'fontname',' 隶书' ,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9],'string' ,{ ' 信号的分解与合成' });

h_push9=uicontrol(h_fig, 'style' , 'push' , ...
'unit' , 'normalized' , 'position' ,[0.62,0.30,0.12,0.08], ...
'string' , '仿 真 十 二' ,'backgroundcolor',[0.7 0.7 0.9],'fontname','行书','fontsize',12 , 'callback' , 'zqxhpp' );
h_text=uicontrol(h_fig, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.75,0.30,0.36,0.06], ...
'horizontal' , 'left' , 'fontsize' ,12,'fontname',' 隶书' ,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9],'string' ,{ ' 周期信号的频谱表示' });

h_push13=uicontrol(h_fig, 'style' , 'push' , ...
'unit' , 'normalized' , 'position' ,[0.62,0.19,0.12,0.08], ...
'string' , '仿 真 十 三' ,'backgroundcolor',[0.7 0.7 0.9],'fontname','行书','fontsize',12 , 'callback' , 'ltipvxy' );
h_text=uicontrol(h_fig, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.75,0.19,0.36,0.06], ...
'horizontal' , 'left' , 'fontsize' ,12,'fontname',' 隶书' ,'foregroundcolor','blue','backgroundcolor',[0.7 0.7 0.9],'string' ,{ ' LTI系统的频率响应' });

h_push10=uicontrol(h_fig, 'style' , 'push' , ...
'unit' , 'normalized' , 'position' ,[0.62,0.08,0.28,0.08], ...
'string' , '返  回  上  一  页' ,'fontname','楷书','fontsize',14 ,'foregroundcolor',[0.9 0.2 0.4],'backgroundcolor',[0.7 0.7 0.9], 'callback' , 'xhxtsy' );


