% Copyright (c) 1997-2000 by TH Technology, Inc.
% All Rights Reserved.
% Date: 2006/01/02
clear
clf reset
set(gcf, 'unit' , 'normalized' , 'position' ,[0.18,0.2,0.65,0.5]);
set(gcf, 'defaultuicontrolunits' , 'normalized' );
set(gcf, 'defaultuicontrolhorizontal' , 'left' );
str='信号的其他运算';
set(gcf, 'name' ,str,'color',[0.7 0.7 0.9], 'numbertitle' , 'off' ); % 书写图形窗名
h_axes=axes( 'position' ,[0.08,0.15,0.53,0.75]); % 定义轴位框位置
%set(h_axes,'Visible','off'); % 隐去坐标轴
xlabel('t(s)');ylabel('幅度(V)');grid on;


h_text=uicontrol(gcf,'Style','frame',...
'unit' , 'normalized' , 'backgroundcolor',[0.4 0.4 0.5], 'position' ,[0.63,0.11,0.355,0.79], ...
'horizontal' , 'left' ,'fontsize' ,11);

h_push1=uicontrol(gcf, 'style' , 'push' , ...
'unit' , 'normalized' ,'foregroundcolor','k','backgroundcolor',[0.3 0.8 0.6], 'position' ,[0.65,0.72,0.15,0.11], ...
'string' , '正弦信号' ,'fontname','行书','fontsize' ,11, 'callback' , 'xhqtys' );
h_push2=uicontrol(gcf, 'style' , 'push' , ...
'unit' , 'normalized' ,'foregroundcolor','k','backgroundcolor',[0.3 0.8 0.6], 'position' ,[0.82,0.72,0.15,0.11], ...
'string' , '余弦信号' ,'fontname','行书','fontsize' ,11, 'callback' , 'xhqtys1' );
h_push3=uicontrol(gcf, 'style' , 'push' , ...
'unit' , 'normalized' , 'foregroundcolor','k','backgroundcolor',[0.3 0.8 0.6],'position' ,[0.65,0.54,0.15,0.11], ...
'fontname','行书','fontsize' ,11,'string' , '单位斜坡信号' , ...
'callback' , 'xhqtys2');
h_push4=uicontrol(gcf, 'style' , 'push' , ...
'unit' , 'normalized' ,'foregroundcolor','k', 'backgroundcolor',[0.3 0.8 0.6],'position' ,[0.82,0.36,0.15,0.11], ...
'string' , '单边指数信号' ,'fontname','行书','fontsize' ,10, 'callback' , 'xhqtys3' );
h_push5=uicontrol(gcf, 'style' , 'push' , ...
'unit' , 'normalized' ,'foregroundcolor','k', 'backgroundcolor',[0.3 0.8 0.6],'position' ,[0.65,0.36,0.15,0.11], ...
'string' , '指数函数信号' ,'fontname','行书','fontsize' ,11,'callback' , 'xhqtys4');
h_push6=uicontrol(gcf, 'style' , 'push' , ...
'unit' , 'normalized' , 'foregroundcolor','k','backgroundcolor',[0.3 0.8 0.6],'position' ,[0.82,0.54,0.15,0.11], ...
'fontname','行书','fontsize' ,11,'string' , '抽样函数信号' , ...
'callback' , 'xhqtys5');
h_push7=uicontrol(gcf, 'style' , 'push' , ...
'unit' , 'normalized' , 'foregroundcolor','k','backgroundcolor',[0.3 0.8 0.6],'position' ,[0.65,0.18,0.15,0.11], ...
'fontname','行书','fontsize' ,11,'string' , '矩形波信号' , ...
'callback' , 'xhqtys6');
h_push8=uicontrol(gcf, 'style' , 'push' , ...
'unit' , 'normalized' , 'foregroundcolor','k','fontname','行书','fontsize' ,11,'backgroundcolor',[0.9 0.7 0.6],'position' ,[0.82,0.18,0.15,0.11], ...
'string' , '返回目录' ,'callback' , 'xhdjbys');