# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clientui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_clientui(object):
    def setupUi(self, clientui):
        clientui.setObjectName("clientui")
        clientui.resize(500, 400)
        self.textEdit = QtWidgets.QTextEdit(clientui)
        self.textEdit.setGeometry(QtCore.QRect(120, 100, 320, 100))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(clientui)
        self.textEdit_2.setGeometry(QtCore.QRect(120, 220, 320, 100))
        self.textEdit_2.setObjectName("textEdit_2")
        self.lineEdit = QtWidgets.QLineEdit(clientui)
        self.lineEdit.setGeometry(QtCore.QRect(120, 30, 250, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(clientui)
        self.label.setGeometry(QtCore.QRect(10, 40, 100, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(clientui)
        self.label_2.setGeometry(QtCore.QRect(10, 120, 91, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(clientui)
        self.label_3.setGeometry(QtCore.QRect(10, 230, 72, 15))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(clientui)
        self.pushButton.setGeometry(QtCore.QRect(80, 350, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(clientui)
        self.pushButton_2.setGeometry(QtCore.QRect(290, 350, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(clientui)
        self.pushButton_3.setGeometry(QtCore.QRect(390, 30, 73, 28))
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(clientui)
        QtCore.QMetaObject.connectSlotsByName(clientui)

    def retranslateUi(self, clientui):
        _translate = QtCore.QCoreApplication.translate
        clientui.setWindowTitle(_translate("clientui", "2019217864"))
        self.label.setText(_translate("clientui", "服务器IP："))
        self.label_2.setText(_translate("clientui", "要加密的明文："))
        self.label_3.setText(_translate("clientui", "加密的密文："))
        self.pushButton.setText(_translate("clientui", "发送"))
        self.pushButton_2.setText(_translate("clientui", "退出"))
        self.pushButton_3.setText(_translate("clientui", "连接"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_clientui()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())